---
title: "master environment"
wordClasses:
  - "noun"
tags:
  - "cloud"
synonyms: []
relatedTerms: []
definition: |
 On Adobe Commerce on cloud infrastructure, Pro projects use an active Platform as a Service (PaaS) environment called master that includes a copy of your Production environment database and web server.
 