# Copyright 2024 Adobe. All rights reserved.
# Licensed under the MIT License. See license.md for details.

# frozen_string_literal: true

source 'https://rubygems.org'

gem 'adobe-comdox-exl-rake-tasks', git: 'https://github.com/commerce-docs/adobe-comdox-exl-rake-tasks', tag: 'v0.3.0'
gem 'faraday-retry'
gem 'whatsup_github', git: 'https://github.com/commerce-docs/whatsup_github', tag: 'v1.2.0'
