# frozen_string_literal: true

source 'https://rubygems.org'

gem 'jekyll'
gem 'rake'
gem 'whatsup_github', git: 'https://github.com/commerce-docs/whatsup_github', branch: 'main'
gem 'faraday-retry'
gem 'image_optim'
gem 'image_optim_pack'
gem 'ostruct'
gem 'logger'
