#!/bin/bash

set -e

# Verify Jekyll installation
gem list --silent --installed --exact jekyll || gem install jekyll

# Render the templates with data and write results to '_jekyll/_rendered'
jekyll build --disable-disk-cache --destination _rendered

# Copy the rendered files from '_jekyll/_rendered' to 'help/_includes'
# and replace file extensions from .html to .md
for file in *.html; do
    cp _rendered/"$file" ../help/_includes/"$(basename "$file" .html).md"
done
