---
# This file is being used in SWAT automation. Follow existing format to avoid breaking changes.
# If breaking changes cannot be omitted, communicate with the SWAT team prior to introducing them.

extensions:
  Adobe I/O Events for Adobe Commerce:
    docs:
      Composer: https://developer.adobe.com/commerce/extensibility/events/installation/
      Release Notes: https://developer.adobe.com/commerce/extensibility/events/release-notes/
    support:
      - core: 2.4.8
        version: 1.8+
      - core: 2.4.7
        version: 1.5+
      - core: 2.4.6
        version: 1.5+
      - core: 2.4.5
        version: 1.5+
      - core: 2.4.4
        version: 1.5+
  Adobe Commerce Admin UI SDK:
    docs:
      Composer: https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/installation/
      Release Notes: https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/release-notes/
    support:
      - core: 2.4.8
        version: 2.0+
      - core: 2.4.7
        version: 1.3+
      - core: 2.4.6
        version: 1.3+
      - core: 2.4.5
        version: 1.3+
      - core: 2.4.4
        version: '-'
  Adobe Commerce Webhooks:
    docs:
      Composer: https://developer.adobe.com/commerce/extensibility/webhooks/installation/
      Release Notes: https://developer.adobe.com/commerce/extensibility/webhooks/release-notes/
    support:
      - core: 2.4.8
        version: 1.5+
      - core: 2.4.7
        version: 1.2+
      - core: 2.4.6
        version: 1.2+
      - core: 2.4.5
        version: 1.2+
      - core: 2.4.4
        version: 1.2+
  Adobe Experience Manager Assets Integration for Commerce:
    docs:
      Composer: https://experienceleague.adobe.com/en/docs/commerce-admin/content-design/aem-asset-management/getting-started/aem-assets-configure-commerce
      Release Notes: https://experienceleague.adobe.com/en/docs/commerce-admin/content-design/aem-asset-management/aem-assets-release-notes
    support:
      - core: 2.4.8
        version: 1.0.20+
      - core: 2.4.7
        version: 1.0.20+
      - core: 2.4.6
        version: 1.0.20+
      - core: 2.4.5
        version: 1.0.20+
      - core: 2.4.4
        version: 1.0.20+
  Audience Activation:
    docs:
      Marketplace: https://commercemarketplace.adobe.com/magento-audiences.html
      Release Notes: https://experienceleague.adobe.com/en/docs/commerce-admin/customers/audience-activation#release-notes
    support:
      - core: 2.4.8
        version: 1.0.0+
      - core: 2.4.7
        version: 1.0.0+
      - core: 2.4.6
        version: 1.0.0+
      - core: 2.4.5
        version: 1.0.0+
      - core: 2.4.4
        version: 1.0.0+
  B2B:
    docs:
      Composer: https://experienceleague.adobe.com/en/docs/commerce-admin/b2b/install
      Release Notes: https://experienceleague.adobe.com/en/docs/commerce-admin/b2b/release-notes
    support:
      - core: 2.4.8
        version: 1.5.2
      - core: 2.4.7
        version: 1.5+, 1.4+
      - core: 2.4.6
        version: 1.5+, 1.4+, 1.3.5+
      - core: 2.4.5
        version: 1.3.4
      - core: 2.4.4
        version: 1.3.3
  Data Connection:
    docs:
      Marketplace: https://commercemarketplace.adobe.com/magento-experience-platform-connector.html
      Release Notes: https://experienceleague.adobe.com/en/docs/commerce/data-connection/release-notes
    support:
      - core: 2.4.8
        version: 3.3.0+
      - core: 2.4.7
        version: 3.1.1+
      - core: 2.4.6
        version: 2.1.1+
      - core: 2.4.5
        version: 1.0.0+
      - core: 2.4.4
        version: 1.0.0+
  Page Builder:
    docs:
      User Guide: https://experienceleague.adobe.com/en/docs/commerce-admin/page-builder/guide-overview
      Release Notes: https://experienceleague.adobe.com/en/docs/commerce-admin/page-builder/release-notes
    support:
      - core: 2.4.8
        version: '-'
      - core: 2.4.7
        version: '-'
      - core: 2.4.6
        version: 1.7.3
      - core: 2.4.5
        version: 1.7.2
      - core: 2.4.4
        version: 1.7.1
services:
  Catalog Service for Adobe Commerce:
    docs:
      Overview: https://experienceleague.adobe.com/en/docs/commerce/catalog-service/guide-overview
      Release Notes: https://experienceleague.adobe.com/en/docs/commerce/catalog-service/release-notes
    support:
      - core: 2.4.8
        version: 1.32
      - core: 2.4.7
        version: 1.32
      - core: 2.4.6
        version: 1.32
      - core: 2.4.5
        version: 1.32
      - core: 2.4.4
        version: 1.32
  Live Search:
    docs:
      Marketplace: https://commercemarketplace.adobe.com/magento-live-search.html
      Release Notes: https://experienceleague.adobe.com/en/docs/commerce/live-search/release-notes
    support:
      - core: 2.4.8
        version: 4.3.0
      - core: 2.4.7
        version: 4.3.0
      - core: 2.4.6
        version: 4.3.0
      - core: 2.4.5
        version: 4.3.0
      - core: 2.4.4
        version: 4.3.0
  Payment Services:
    docs:
      Marketplace: https://commercemarketplace.adobe.com/magento-payment-services.html
      Release Notes: https://experienceleague.adobe.com/en/docs/commerce/payment-services/release-notes
    support:
      - core: 2.4.8
        version: 2.11.0 (PHP 8.3)
      - core: 2.4.7
        version: 2.10.0 (PHP 8.3)
      - core: 2.4.6
        version: 2.5.0 (PHP 8.2)
      - core: 2.4.5
        version: 2.4.0 (PHP 8.1)
      - core: 2.4.4
        version: 2.4.0 (PHP 8.1)
  Product Recommendations:
    docs:
      Marketplace: https://commercemarketplace.adobe.com/magento-product-recommendations.html
      Release Notes: https://experienceleague.adobe.com/en/docs/commerce/product-recommendations/release-notes
    support:
      - core: 2.4.8
        version: 6.2.0
      - core: 2.4.7
        version: 6.2.0
      - core: 2.4.6
        version: 6.2.0
      - core: 2.4.5
        version: 6.2.0
      - core: 2.4.4
        version: 6.2.0
