---
##### Aggregate Commerce Issues into one Project #####

name: Add issues

on:
  issues:
    types: [opened, reopened]

jobs:
  add-to-project:
    name: Add to Commerce project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/AdobeDocs/projects/6 # The organizational project for issues
          github-token: ${{ secrets.COMMERCE_PROJECT_AUTOMATION }}
